<?php
// module/Album/view/album/album/add.phtml:

$title = 'Ajouter la note au etudiant';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php


$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nom_prenom'));
echo $this->formRow($form->get('note'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();