<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script>

    function supalb(lib) {
         alert('rt');
    
$.ajax({
  url      : document.location.protocol + '//localhost/zendmaster/public/album/answer/'+lib,
  dataType : 'json',
  success  : function (data) {                
            alert("popo");

  }
                
          
});

}
//Call AJAX:
//$(document).ready(supalb());



</script>



<?php
// module/Album/view/album/album/index.phtml:

$title = 'Liste des notes des etudiant';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('album', array(
        'action'=>'add'));?>">Ajouter une note</a></p>

<table class="table">
<tr>
    <th>Nom et prenom d'etudiant</th>
    <th>Note</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($albums as $etudiant) : ?>
<tr>
    <td><?php echo $this->escapeHtml($etudiant->nom_prenom);?></td>
    <td><?php echo $this->escapeHtml($etudiant->note);?></td>    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $etudiant->id));?>">Edit</a>
        <a onClick="supalb(<?php echo $etudiant->id?>);" href="">
            
            Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>